### ISSUE TITLE
Event mapper consumer fails to process all records on internal error

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria-connector-ibm-information-server#324]
Can be reproduced in scenario where new events arrive on the topic while consumer/application is temporary down. Once the consumer is up and running again it will fetch the records and try to process them in a for loop block. The processing of event can return with an error and break the loop therefore skip processing of the remaining events which in turn due to the auto-commit policy used are already committed on the server.

Looks like this can be fixed with improved error handling but we can also use it as opportunity to enhance the event mapper kafka consumer by tuning the offset management part.

**Comment by cmgrote** [comment]
Investigating addressing this through the following changes:

- Setting `max.poll.records` to 1, to ensure that the `poll` only retrieves a single record at a time (and therefore if there is a failure, it only impacts that single record)
- Setting `enable.auto.commit` to false, to ensure that offsets are only committed when explicitly committed
- Synchronously committing the offset after each record is processed
- Also setting the consumer's group ID based on the unique metadata collection ID -- so that what is registered and the offset management is unique to a given metadata collection rather than being the same across all proxy instances

These changes should also allow us to pickup any events generated within IGC if the proxy is offline for some short timespan and restarts (ie. events generated by IGC while the proxy is offline should not be lost, unless a significant amount of time passes in between and the Kafka topic eventually evicts them).

The polling changes could, however, have the potential to negatively impact performance -- so testing out to see if there is a significant degradation.

**Comment by cmgrote** [comment]
This should now be (initially) addressed in master -- suggest we continue testing with what's there now, and raise any new issues on any other options / degradation that is discovered and needs to be addressed.
